explain how to run the project from git
canonical/charmcraft pull request #144
Opened 2020-08-27 19:14 UTC by dstathis

fixes: #88

2020-08-31 12:43 UTC, facundobatista commented on README.md
> +    PYTHONPATH=.:${PYTHONPATH} python charmcraft/main.py
`python -m charmcraft` is shorter and more to the point (no need to fix paths, or call internal modules)

2020-08-31 12:44 UTC, facundobatista commented on README.md
> +    PYTHONPATH=.:${PYTHONPATH} ./run_tests
`./run_tests` should be enough, not path mangling needed...

2020-09-01 14:16 UTC, chipaca requested changes
This is a good idea, but it needs a small tweak so you can actually copy-paste the code into a terminal (and people will).

2020-09-01 14:16 UTC, chipaca commented on README.md
> +    git clone https://github.com/canonical/charmcraft.git
```suggestion
    git clone https://github.com/canonical/charmcraft.git
    cd charmcraft
```

2020-09-01 14:32 UTC, dstathis commented on README.md
> +    git clone https://github.com/canonical/charmcraft.git
Good catch

2020-09-01 14:34 UTC, chipaca approved these changes

2020-09-01 14:44 UTC, merged