make revision a positional argument to release
canonical/charmcraft pull request #149
Opened 2020-09-03 21:08 UTC by dstathis

fixes: #127

2020-09-09 18:17 UTC, facundobatista requested changes
This is not just a matter of making the parameter mandatory. You also need to remove the code that deals for this arg not being present, and adjust tests.

Also, add a comment to remove the corresponding case in https://docs.google.com/document/d/1Pe-0ED6db53SmrUGIAgVMzxeCOGJQwsZJWf7jzFSagQ/

And also fix `completion.bash` file

2020-09-16 18:51 UTC, facundobatista requested changes
Almost done, great! Please check the inline comment, and remember to fix the `completion.bash` file.

2020-09-16 18:51 UTC, facundobatista commented on charmcraft/commands/store/__init__.py
> +
Please remove this empty line.

2020-09-21 15:24 UTC, dstathis commented on charmcraft/commands/store/__init__.py
> +
Done.

2020-09-21 21:03 UTC, facundobatista approved these changes
Great, thanks! FTR, I already updated the doc after your suggestion there.

2020-09-22 11:58 UTC, chipaca approved these changes

2020-09-22 12:29 UTC, merged