chore: two small non-code changes
canonical/charmcraft pull request #2028
Opened 2024-12-11 18:02 UTC by lengau

2024-12-11 18:49 UTC, bepri requested changes
oops

2024-12-11 18:49 UTC, bepri commented on .gitignore
> +# `snapcraft try` can be very usefil
```suggestion
# `snapcraft try` can be very useful
```

2024-12-11 19:52 UTC, bepri approved these changes

2024-12-12 14:34 UTC, mr-cal approved these changes

2024-12-12 21:26 UTC, merged