commands/build: charm file name format support for bases (CRAFT-66)
canonical/charmcraft pull request #383
Opened 2021-06-14 16:24 UTC by cjp256

Maintain current format as "legacy" until we have the (default) bases
configuration available in upcoming PRs. Note that only the legacy
path is utilized at runtime, with tests added for bases configuration
support.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

2021-06-14 17:56 UTC, sergiusens commented on charmcraft/commands/build.py
> +    :returns: File name string, including .zip extension.
.zip?

2021-06-14 18:01 UTC, sergiusens approved these changes
Please ensure the docstring mentioned in the inline review is correct.

2021-06-14 18:01 UTC, facundobatista requested changes
Something to fix, a question, and a suggestion.

FTR, I will simplify the code. When you create a function that is only a line of code, used in only one place, and not even tested separatedly, why to have that line of code separated? It just adds overhead to the code reading.

2021-06-14 18:13 UTC, cjp256 commented on charmcraft/commands/build.py
> +    *, charm_name: str, bases_config: Optional[BasesConfiguration] = None
Both parameters will be required soon.

2021-06-14 18:13 UTC, cjp256 commented on charmcraft/commands/build.py
> +        [base.name, base.channel, _format_architectures(base.architectures)]
Done!

2021-06-14 18:13 UTC, cjp256 commented on charmcraft/commands/build.py
> +    :returns: File name string, including .zip extension.
Indeed, fixed!

2021-06-14 18:13 UTC, cjp256 commented on charmcraft/commands/build.py
> +    :returns: File name string, including .zip extension.
Fixed!

2021-06-14 18:31 UTC, cjp256 commented on charmcraft/commands/build.py
> +    *, charm_name: str, bases_config: Optional[BasesConfiguration] = None
Removed parameter naming.

2021-06-14 19:02 UTC, cmatsuoka approved these changes
Looks good!

2021-06-15 11:33 UTC, facundobatista approved these changes
Great, thanks!

2021-06-15 14:05 UTC, merged