env: only require snap (or dev mode) for Linux (CRAFT-498)
canonical/charmcraft pull request #518
Opened 2021-09-01 13:14 UTC by cjp256

Add a platform check for Linux before vetting that Charmcraft is
running from the snap (or running in developer mode).

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

2021-09-01 14:25 UTC, facundobatista requested changes
Please add a test for this, thanks!

2021-09-01 19:31 UTC, cjp256 commented
I reworked this and updated tests.

2021-09-02 12:54 UTC, cmatsuoka approved these changes
Looks good, with Facundo's suggested change.

2021-09-02 13:17 UTC, cjp256 commented on charmcraft/env.py
> +    elif sys.platform in ["win32"]:
I expect darwin to be added to that list. I just didn't want to do it without further testing :D

2021-09-02 13:18 UTC, cjp256 commented on charmcraft/env.py
> +    elif sys.platform in ["win32"]:
done.

2021-09-02 13:20 UTC, facundobatista approved these changes
Thanks!

2021-09-02 13:27 UTC, merged