Add name argument for upload command
canonical/charmcraft pull request #684
Opened 2022-02-23 08:38 UTC by morphis

In some cases the name of the charm a user wants to upload is not the
same as the one specified in metadata.yaml. Specifically for charms
imported into charmhub from the old charmstore this isn't true if they
formerly namespaces (e.g. cs:~foo/bar become foo-bar but charm name
remains foo in metadata.yaml).

To allow charms to be still uploaded in this case a --name option is
added to the upload command which allows a user to specify the exact
name of the charm he wants to upload to rather than letting charmcraft
automatically extract the name from the metadata.yaml file

Fixes #681

2022-03-01 00:36 UTC, hloeung commented
@facundobatista or anyone else from the team able to take a look?

2022-03-03 13:12 UTC, facundobatista requested changes
Great, thanks for this PR!!! I annotated a couple of details inside. Thanks again!

2022-03-03 13:12 UTC, facundobatista commented on charmcraft/commands/store/__init__.py
> +            help="Name of the charm on Charmhub to upload to",
it can be a bundle too, so maybe say "Name of the charm/bundle on ..."?

2022-03-03 13:12 UTC, facundobatista commented on charmcraft/commands/store/__init__.py
> +            name = parsed_args.name
`parsed_args` will always have `name`, in `None` if the user didn't pass it. So you could just do `if parsed_args.name:`...

2022-03-03 13:12 UTC, facundobatista commented on charmcraft/commands/store/__init__.py
>          name = get_name_from_zip(parsed_args.filepath)
This is not necessary if the user indicated the name through the option.

2022-03-03 13:12 UTC, facundobatista commented on tests/commands/test_store_commands.py
> +    """Simple upload, success result."""
This docstring is misleading, adapt it to this test (explain the case that is being tested).

2022-03-03 14:21 UTC, facundobatista approved these changes
Awesome, thank you!

2022-03-03 14:52 UTC, merged